# Generated by Django 2.1.1 on 2018-09-27 13:38

import django.contrib.gis.db.models.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PowerPlant',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('plant', models.CharField(max_length=255)),
                ('country', models.CharField(max_length=255)),
                ('total_power', models.CharField(max_length=255)),
                ('type_of', models.CharField(max_length=255)),
                ('status', models.CharField(max_length=255)),
                ('power_mw', models.FloatField()),
                ('power_cat', models.FloatField()),
                ('built', models.FloatField()),
                ('connected', models.CharField(max_length=255)),
                ('link', models.CharField(max_length=255)),
                ('lon', models.FloatField()),
                ('lat', models.FloatField()),
                ('elev', models.FloatField()),
                ('image', models.CharField(max_length=255)),
                ('mpoly', django.contrib.gis.db.models.fields.PointField(srid=4326)),
            ],
        ),
    ]
