# Generated by Django 2.1.1 on 2018-09-27 14:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('geo_backend', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='powerplant',
            name='shp_id',
            field=models.CharField(default='NULL', max_length=255),
        ),
    ]
