from django.contrib.gis.db import models

class PowerPlant(models.Model):
    shp_id =  models.CharField(max_length=255, default="NULL")
    name = models.CharField(max_length=255)
    plant = models.CharField(max_length=255)
    country = models.CharField(max_length=255)
    total_power = models.CharField(max_length=255)
    type_of = models.CharField(max_length=255)
    status = models.CharField(max_length=255)
    power_mw = models.FloatField()
    power_cat = models.FloatField()
    built = models.FloatField()
    connected = models.CharField(max_length=255)
    link = models.CharField(max_length=255)
    lon = models.FloatField()
    lat = models.FloatField()
    elev = models.FloatField()
    image = models.CharField(max_length=255)

    mpoly = models.PointField()

    # Returns the string representation of the model.
    def __str__(self):
        return self.name


class WorldStates(models.Model):
    featurecla = models.CharField(max_length=15)
    scalerank = models.IntegerField()
    labelrank = models.IntegerField()
    sovereignt = models.CharField(max_length=32)
    sov_a3 = models.CharField(max_length=3)
    adm0_dif = models.IntegerField()
    level = models.IntegerField()
    type = models.CharField(max_length=17)
    admin = models.CharField(max_length=35)
    adm0_a3 = models.CharField(max_length=3)
    geou_dif = models.IntegerField()
    geounit = models.CharField(max_length=35)
    gu_a3 = models.CharField(max_length=3)
    su_dif = models.IntegerField()
    subunit = models.CharField(max_length=35)
    su_a3 = models.CharField(max_length=3)
    brk_diff = models.IntegerField()
    name = models.CharField(max_length=25)
    name_long = models.CharField(max_length=35)
    brk_a3 = models.CharField(max_length=3)
    brk_name = models.CharField(max_length=32)
    brk_group = models.CharField(max_length=17)
    abbrev = models.CharField(max_length=13)
    postal = models.CharField(max_length=4)
    formal_en = models.CharField(max_length=52)
    formal_fr = models.CharField(max_length=35)
    name_ciawf = models.CharField(max_length=45)
    note_adm0 = models.CharField(max_length=22)
    note_brk = models.CharField(max_length=51)
    name_sort = models.CharField(max_length=35)
    name_alt = models.CharField(max_length=14)
    mapcolor7 = models.IntegerField()
    mapcolor8 = models.IntegerField()
    mapcolor9 = models.IntegerField()
    mapcolor13 = models.IntegerField()
    pop_est = models.BigIntegerField()
    pop_rank = models.IntegerField()
    gdp_md_est = models.FloatField()
    pop_year = models.IntegerField()
    lastcensus = models.IntegerField()
    gdp_year = models.IntegerField()
    economy = models.CharField(max_length=26)
    income_grp = models.CharField(max_length=23)
    wikipedia = models.IntegerField()
    fips_10_field = models.CharField(max_length=3)
    iso_a2 = models.CharField(max_length=3)
    iso_a3 = models.CharField(max_length=3)
    iso_a3_eh = models.CharField(max_length=3)
    iso_n3 = models.CharField(max_length=3)
    un_a3 = models.CharField(max_length=4)
    wb_a2 = models.CharField(max_length=3)
    wb_a3 = models.CharField(max_length=3)
    woe_id = models.IntegerField()
    woe_id_eh = models.IntegerField()
    woe_note = models.CharField(max_length=167)
    adm0_a3_is = models.CharField(max_length=3)
    adm0_a3_us = models.CharField(max_length=3)
    adm0_a3_un = models.IntegerField()
    adm0_a3_wb = models.IntegerField()
    continent = models.CharField(max_length=23)
    region_un = models.CharField(max_length=23)
    subregion = models.CharField(max_length=25)
    region_wb = models.CharField(max_length=26)
    name_len = models.IntegerField()
    long_len = models.IntegerField()
    abbrev_len = models.IntegerField()
    tiny = models.IntegerField()
    homepart = models.IntegerField()
    min_zoom = models.FloatField()
    min_label = models.FloatField()
    max_label = models.FloatField()
    ne_id = models.BigIntegerField()
    wikidataid = models.CharField(max_length=8)
    name_ar = models.CharField(max_length=72)
    name_bn = models.CharField(max_length=125)
    name_de = models.CharField(max_length=46)
    name_en = models.CharField(max_length=44)
    name_es = models.CharField(max_length=44)
    name_fr = models.CharField(max_length=54)
    name_el = models.CharField(max_length=88)
    name_hi = models.CharField(max_length=123)
    name_hu = models.CharField(max_length=41)
    name_id = models.CharField(max_length=46)
    name_it = models.CharField(max_length=44)
    name_ja = models.CharField(max_length=63)
    name_ko = models.CharField(max_length=47)
    name_nl = models.CharField(max_length=46)
    name_pl = models.CharField(max_length=47)
    name_pt = models.CharField(max_length=43)
    name_ru = models.CharField(max_length=86)
    name_sv = models.CharField(max_length=42)
    name_tr = models.CharField(max_length=42)
    name_vi = models.CharField(max_length=56)
    name_zh = models.CharField(max_length=36)
    geom = models.MultiPolygonField(srid=4326)